### ISSUE TITLE
New maintainer needed.

### ISSUE THREAD

**Issue by wraithgar** [kjellmorten/hapi-json-api#43]
I don't really use this in any of my projects anymore and do not have the time to maintain it.

Currently this module has very very light responsibilities, which is mostly managing pull requests from greenkeeper.

If you are interested in taking this module over please leave a comment in this issue.

**Comment by kjellmorten** [comment]
Hi, @wraithgar!

I would be interested in maintaining this project. My focus these days are on APIs, and Hapi and JSON-API have become my go-tos for REST APIs. So this is a good fit for me.

Are you planning to stay involved in the project or leave it entirely?

**Comment by wraithgar** [comment]
Howdy @kjellmorten! I do not intend to be involved in the project at all.

**Comment by kjellmorten** [comment]
Ok, no worries. I can take this off your shoulders. :)

**Comment by wraithgar** [comment]
What is your npm username?  Do you mind if I transfer this repo to your account?

**Comment by kjellmorten** [comment]
Please do. It's @kjellmorten, just as on Github.
