### ISSUE TITLE
ETA for updated deps

### ISSUE THREAD

**Issue by binarymist** [kjellmorten/hapi-json-api#51]
Hi there. Just wondering when the deps are likely to be updated: https://nodesecurity.io/orgs/laboreum/projects/933c42d1-7af0-4d0b-82b5-08c4915afe6b/master

Thanks.

**Comment by kjellmorten** [comment]
Sorry for the late reaction here, @binarymist. It will happen this week.

**Comment by kjellmorten** [comment]
Hi, @binarymist.

Just released 2.0.6, with the minor updates on all deps, including Hoek, that had a vulnerability issue.

I'm planning a 3.0 release soon, for Hapi 17 and major updates on the other deps. Feel free to make suggestions if there are other changes you would like in 3.0.

Thanks!
